### PR TITLE
change draft to create table with sorted columns

### PR DESCRIPTION
**Pull request by ff2u**
It's a draft version of a python script, setting a basis for sorted columns in fpangels page.

### CODE REVIEW

**Comment by StefanBrand** [comment]
To be honest, I don't like tables because they usually aren't very responsive. What happens when the screen is quite narrow? ~450px/FP1

**Comment by ff2u** [comment]
You may be right, and tables are AFAIK deprecated in web development anyway.
So a list in combination with a sorting Javascript might do the trick too...

**Comment by StefanBrand** [comment]
Does sortable.js only work with tables? If yes, we might craft something with [d3-selection](https://github.com/d3/d3-selection/blob/v1.4.0/README.md#selection_sort).


-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 12. November 2019 23:20:28 MEZ schrieb ff2u <notifications@github.com>:
>You may be right, and tables are AFAIK deprecated in web development
>anyway.
>So a list in combination with a sorting Javascript might do the trick
>too...

**Comment by ff2u** [comment]
I'm considering to try out https://listjs.com/
Also the search field sounds like a nice gimmick here for me.

**Comment by StefanBrand** [comment]
Yep, but we'd need Reverse Geocoding to sort by nearest heaven (otherwise we depend on correct spelling of user). Mind to open a separate issue for this?



-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 13. November 2019 08:14:01 MEZ schrieb ff2u <notifications@github.com>:
>I'm considering to try out https://listjs.com/
>Also the search field sounds like a nice gimmick here for me.

**Comment by ff2u** [comment]
What is "this" referring to?

**Comment by StefanBrand** [comment]
By "this" I mean a search field. :)

**Comment by ff2u** [comment]
While "searching for nearest heaven" really sounds cool and worth a separate "issue" I was just referring to a search field searching in the list (e.g. you can type in "Madrid" if you're interested in a Madrid heaven but don't want to search in the whole list yourself). I'd automatically come with the js and I don't think it's worth a separate issue.

**Comment by StefanBrand** [comment]
And I'm saying that a search field is useless in my eyes if I search for "Köln", but the Heaven is called "Rhein-Ruhr".


-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 13. November 2019 08:30:59 MEZ schrieb ff2u <notifications@github.com>:
>While "searching for nearest heaven" really sounds cool and worth a
>separate "issue" I was just referring to a search field searching in
>the list (e.g. you can type in "Madrid" if you're interested in a
>Madrid heaven but don't want to search in the whole list yourself). I'd
>automatically come with the js and I don't think it's worth a separate
>issue.

**Comment by ff2u** [comment]
A solution using tables is no longer followed.

**Pull request closed without merging**
